version: "3.8"
services:
  mqtt-broker:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    volumes:
      - ./mqtt-broker/config:/mosquitto/config
      - ./mqtt-broker/data:/mosquitto/data
      - ./mqtt-broker/log:/mosquitto/log
    ports:
      - "1883:1883"

  database:
    build: ./database
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Scam@1992
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - ./database:/var/opt/mssql

  gateway:
    build: ./gateway
    container_name: gateway
    depends_on:
      - mqtt-broker
    ports:
      - "4840:4840"

  machine-1:
    build: ./machine-1
    container_name: machine1-sensor
    depends_on:
      - gateway
    environment:
      - OPCUA_SERVER_URL=opc.tcp://gateway:4840
      - MACHINE_ID=Machine1
      - SAMPLE_INTERVAL=30
      - NAMESPACE=SENSOR_DATA

  machine-2:
    build: ./machine-2
    container_name: machine2-sensor
    depends_on:
      - gateway
    environment:
      - OPCUA_SERVER_URL=opc.tcp://gateway:4840
      - MACHINE_ID=Machine2
      - SAMPLE_INTERVAL=15
      - NAMESPACE=SENSOR_DATA

  mqtt-client:
    build: ./mqtt-client
    container_name: mqtt-client
    depends_on:
      - mqtt-broker
      - database
    environment:
      - MQTT_BROKER=mqtt-broker
      - MQTT_PORT=1883
      - DB_SERVER=mssql
      - DB_DATABASE=SensorDB
      - DB_USERNAME=sa
      - DB_PASSWORD=Scam@1992
      - DB_DRIVER=ODBC Driver 17 for SQL Server

